# Generated by Django 3.2.6 on 2021-11-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sba_Schlafbetreudender_Arzt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sba_Vorhanden', models.BooleanField()),
                ('sba_Name', models.CharField(max_length=55)),
                ('sba_Fachrichtung', models.CharField(max_length=55)),
                ('sba_plz', models.IntegerField()),
                ('sba_Ort', models.CharField(max_length=55)),
                ('sba_Straße', models.CharField(max_length=55)),
            ],
        ),
        migrations.RenameField(
            model_name='p_patient',
            old_name='Geburtsdatum',
            new_name='p_Geburtsdatum',
        ),
        migrations.RenameField(
            model_name='p_patient',
            old_name='Geschlecht',
            new_name='p_Geschlecht',
        ),
        migrations.RenameField(
            model_name='p_patient',
            old_name='Nachname',
            new_name='p_Nachname',
        ),
        migrations.RenameField(
            model_name='p_patient',
            old_name='SVNummer',
            new_name='p_SVNummer',
        ),
        migrations.RenameField(
            model_name='p_patient',
            old_name='Vorname',
            new_name='p_Vorname',
        ),
        migrations.RemoveField(
            model_name='f_firma',
            name='PatientID',
        ),
        migrations.RemoveField(
            model_name='p_patient',
            name='Vorscreening',
        ),
    ]
