# Generated by Django 3.2.6 on 2021-11-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0002_auto_20211117_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_patient',
            name='p_ArztID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osa_application.sba_schlafbetreudender_arzt'),
        ),
        migrations.AddField(
            model_name='p_patient',
            name='p_Vorscreening',
            field=models.BooleanField(default=None, max_length=10),
        ),
    ]
