# Generated by Django 3.2.6 on 2021-11-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0003_auto_20211117_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_patient',
            name='p_ArztID',
        ),
    ]
