# Generated by Django 3.2.6 on 2021-11-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0004_remove_p_patient_p_arztid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_patient',
            name='p_Vorscreening',
        ),
    ]
