# Generated by Django 3.2.6 on 2021-11-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0006_auto_20211117_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_patient',
            old_name='p_Arzt',
            new_name='Arzt',
        ),
        migrations.RenameField(
            model_name='p_patient',
            old_name='p_Geburtsdatum',
            new_name='Geburtsdatum',
        ),
        migrations.RenameField(
            model_name='p_patient',
            old_name='p_Geschlecht',
            new_name='Geschlecht',
        ),
        migrations.RenameField(
            model_name='p_patient',
            old_name='p_Nachname',
            new_name='Nachname',
        ),
        migrations.RenameField(
            model_name='p_patient',
            old_name='p_SVNummer',
            new_name='SVNummer',
        ),
        migrations.RenameField(
            model_name='p_patient',
            old_name='p_Vorname',
            new_name='Vorname',
        ),
        migrations.RenameField(
            model_name='p_patient',
            old_name='p_Vorscreening',
            new_name='Vorscreening',
        ),
        migrations.RenameField(
            model_name='sba_schlafbetreudender_arzt',
            old_name='sba_Straße',
            new_name='sba_Strasse',
        ),
    ]
