# Generated by Django 3.2.6 on 2021-11-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0007_auto_20211117_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sa_schlafbetreuenderarzt',
            name='PatientID',
        ),
    ]
