# Generated by Django 3.2.6 on 2021-11-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0009_remove_p_patient_arzt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sa_schlafbetreuenderarzt',
            old_name='Straße',
            new_name='Strasse',
        ),
    ]
