# Generated by Django 3.2.6 on 2021-12-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0012_auto_20211129_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ASV',
        ),
        migrations.DeleteModel(
            name='autoBitLevel',
        ),
        migrations.DeleteModel(
            name='AVAPS',
        ),
        migrations.RemoveField(
            model_name='com_compliance',
            name='PatientID',
        ),
        migrations.DeleteModel(
            name='CPAP_Einstellung',
        ),
        migrations.DeleteModel(
            name='CPAP_Kontrolle',
        ),
        migrations.DeleteModel(
            name='DiagnosePSG',
        ),
        migrations.DeleteModel(
            name='Firma',
        ),
        migrations.DeleteModel(
            name='Gerät',
        ),
        migrations.DeleteModel(
            name='Masken',
        ),
        migrations.DeleteModel(
            name='Schlafbetreudender_Arzt',
        ),
        migrations.DeleteModel(
            name='Spontanous',
        ),
        migrations.DeleteModel(
            name='Spontanous_Timed',
        ),
        migrations.DeleteModel(
            name='Therapieabbruch',
        ),
        migrations.DeleteModel(
            name='Vorscreening',
        ),
        migrations.AddField(
            model_name='patient',
            name='Gelöscht',
            field=models.BooleanField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='VerändertAm',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='VerändertVon',
            field=models.CharField(default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Geburtsdatum',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Geschlecht',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Nachname',
            field=models.CharField(default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='patient',
            name='SVNummer',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Vorname',
            field=models.CharField(default=None, max_length=55),
        ),
        migrations.DeleteModel(
            name='com_Compliance',
        ),
    ]
