# Generated by Django 3.2.6 on 2021-12-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0013_auto_20211212_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingabeID', models.IntegerField()),
                ('PatientID', models.IntegerField()),
                ('minEPAP', models.IntegerField()),
                ('maxEPAP', models.IntegerField()),
                ('minPS', models.IntegerField()),
                ('maxPS', models.IntegerField()),
                ('verordnetam', models.DateField()),
            ],
            options={
                'db_table': 'ASV',
            },
        ),
        migrations.CreateModel(
            name='autoBitLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingabeID', models.IntegerField()),
                ('minEPAP', models.IntegerField()),
                ('maxEPAP', models.IntegerField()),
                ('minPS', models.IntegerField()),
                ('maxPS', models.IntegerField()),
            ],
            options={
                'db_table': 'autoBitLevel',
            },
        ),
        migrations.CreateModel(
            name='AVAPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EingabeID', models.IntegerField()),
                ('minEPAP', models.IntegerField()),
                ('maxEPAP', models.IntegerField()),
                ('minPS', models.IntegerField()),
                ('maxPS', models.IntegerField()),
                ('Zielvolumen', models.IntegerField()),
            ],
            options={
                'db_table': 'AVAPS',
            },
        ),
        migrations.CreateModel(
            name='CPAP_Einstellung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.IntegerField()),
                ('Datum_cpap', models.DateField()),
                ('BeatmungsModi', models.CharField(max_length=255)),
                ('IPAP', models.IntegerField()),
                ('EPAP', models.IntegerField()),
                ('Erweitert', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'CPAP_Einstellung',
            },
        ),
        migrations.CreateModel(
            name='CPAP_Kontrolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.IntegerField()),
                ('Datum_1cpap', models.DateField()),
                ('Compliance_1cpap', models.IntegerField()),
                ('durchschnittlicheVerwendungsdauer', models.IntegerField()),
                ('berücksichtigteTage_1CPAP', models.IntegerField()),
                ('restAHibei_1CPAP', models.IntegerField()),
                ('nachjustierungNotwendig', models.BooleanField()),
                ('ModuswechselNotwendig', models.BooleanField()),
            ],
            options={
                'db_table': 'CPAP_Kontrolle',
            },
        ),
        migrations.CreateModel(
            name='DiagnosePSG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datum_Diagnose_PSG', models.DateField()),
                ('BMI_bei_Diagnose_PSG', models.IntegerField()),
                ('SaO2min_PSG', models.IntegerField()),
                ('Dominanz', models.CharField(max_length=255)),
                ('Lageabhängig', models.BooleanField()),
                ('AHI_Gesamt', models.IntegerField()),
                ('REM_assoziert', models.IntegerField()),
                ('O2unter90Prozent', models.IntegerField()),
                ('Diagnose', models.CharField(max_length=255)),
                ('primäre_Therapieempfehlung', models.CharField(max_length=255)),
                ('alternative_Therapieempfehlung', models.CharField(max_length=255)),
                ('Zustimmung_für_Beatmung', models.BooleanField()),
            ],
            options={
                'db_table': 'DiagnosePSG',
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firmenname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Firmen',
            },
        ),
        migrations.CreateModel(
            name='Gerät',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.IntegerField()),
                ('Gerätename', models.CharField(max_length=255)),
                ('Hersteller', models.CharField(max_length=255)),
                ('vertreibendeFirma', models.IntegerField()),
                ('Modi', models.CharField(max_length=255)),
                ('WLB', models.BooleanField()),
                ('Rampe', models.IntegerField()),
                ('O2Anschluss', models.BooleanField()),
                ('Heizschlauch', models.BooleanField()),
                ('Freitext', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Gerät',
            },
        ),
        migrations.CreateModel(
            name='Masken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.IntegerField()),
                ('Maskentyp', models.CharField(max_length=255)),
                ('Maskenname', models.CharField(max_length=255)),
                ('Hersteller', models.CharField(max_length=255)),
                ('Größe', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Masken',
            },
        ),
        migrations.CreateModel(
            name='Schlafbetreudender_Arzt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorhanden', models.BooleanField()),
                ('Name', models.CharField(max_length=55)),
                ('Fachrichtung', models.CharField(max_length=55)),
                ('plz', models.IntegerField()),
                ('Ort', models.CharField(max_length=55)),
                ('Strasse', models.CharField(max_length=55)),
                ('Hausnummer', models.IntegerField()),
                ('Telefonnummer', models.IntegerField()),
                ('Email', models.CharField(max_length=255)),
                ('ArztID', models.IntegerField()),
            ],
            options={
                'db_table': 'Schlafbetreudender_Arzt',
            },
        ),
        migrations.CreateModel(
            name='Spontanous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingabeID', models.IntegerField()),
                ('verordnetam', models.DateField()),
                ('IPAP', models.IntegerField()),
                ('EPAP', models.IntegerField()),
                ('DeltaP', models.IntegerField()),
            ],
            options={
                'db_table': 'Spontanous',
            },
        ),
        migrations.CreateModel(
            name='Spontanous_Timed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingabeID', models.IntegerField()),
                ('Modus', models.CharField(max_length=255)),
                ('IPAP', models.IntegerField()),
                ('EPAP', models.IntegerField()),
                ('Zeitgestinsp', models.IntegerField()),
                ('AF', models.IntegerField()),
            ],
            options={
                'db_table': 'Spontanous_Timed',
            },
        ),
        migrations.CreateModel(
            name='Therapieabbruch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EingabeID', models.IntegerField()),
                ('Datum_Therapieabbruch', models.DateField()),
                ('InfobezogenerTherapieabbruch', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Therapieabbruch',
            },
        ),
        migrations.CreateModel(
            name='Vorscreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PGdurchgeführtvon', models.CharField(max_length=255)),
                ('DatumderPG', models.DateField()),
                ('sao2minPG', models.IntegerField()),
                ('RDI', models.IntegerField()),
                ('EingabeID', models.IntegerField()),
            ],
            options={
                'db_table': 'Vorscreening',
            },
        ),
    ]
