# Generated by Django 3.2.6 on 2021-12-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0014_asv_autobitlevel_avaps_cpap_einstellung_cpap_kontrolle_diagnosepsg_firma_gerät_masken_schlafbetreude'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asv',
            table='osa_ASV',
        ),
        migrations.AlterModelTable(
            name='autobitlevel',
            table='osa_autoBitLevel',
        ),
        migrations.AlterModelTable(
            name='avaps',
            table='osa_AVAPS',
        ),
        migrations.AlterModelTable(
            name='cpap_einstellung',
            table='osa_CPAP_Einstellung',
        ),
        migrations.AlterModelTable(
            name='cpap_kontrolle',
            table='osa_CPAP_Kontrolle',
        ),
        migrations.AlterModelTable(
            name='diagnosepsg',
            table='osa_DiagnosePSG',
        ),
        migrations.AlterModelTable(
            name='firma',
            table='osa_Firmen',
        ),
        migrations.AlterModelTable(
            name='gerät',
            table='osa_Gerät',
        ),
        migrations.AlterModelTable(
            name='masken',
            table='osa_Masken',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='osa_Patient',
        ),
        migrations.AlterModelTable(
            name='schlafbetreudender_arzt',
            table='osa_Schlafbetreudender_Arzt',
        ),
        migrations.AlterModelTable(
            name='spontanous',
            table='osa_Spontanous',
        ),
        migrations.AlterModelTable(
            name='therapieabbruch',
            table='osa_Therapieabbruch',
        ),
        migrations.AlterModelTable(
            name='vorscreening',
            table='osa_Vorscreening',
        ),
    ]
