# Generated by Django 3.2.6 on 2021-12-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0015_auto_20211212_1433'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spontanous_timed',
            table='osa_Spontanous_Timed',
        ),
    ]
