# Generated by Django 3.2.6 on 2021-12-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0017_auto_20211213_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpap_kontrolle',
            old_name='Compliance_1cpap',
            new_name='Compliance_cpap',
        ),
        migrations.RenameField(
            model_name='cpap_kontrolle',
            old_name='Datum_1cpap',
            new_name='Datum_cpap',
        ),
        migrations.RenameField(
            model_name='cpap_kontrolle',
            old_name='berücksichtigteTage_1CPAP',
            new_name='berücksichtigteTage_CPAP',
        ),
        migrations.RenameField(
            model_name='cpap_kontrolle',
            old_name='restAHibei_1CPAP',
            new_name='restAHibei_CPAP',
        ),
        migrations.AddField(
            model_name='spontanous',
            name='PatientID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osa_application.patient'),
        ),
        migrations.AlterField(
            model_name='spontanous',
            name='DeltaP',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='spontanous',
            name='EPAP',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='spontanous',
            name='IPAP',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='spontanous',
            name='eingabeID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='spontanous',
            name='verordnetam',
            field=models.DateField(default=None),
        ),
    ]
