# Generated by Django 3.2.6 on 2021-12-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0018_auto_20211214_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobitlevel',
            name='PatientID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osa_application.patient'),
        ),
        migrations.AddField(
            model_name='avaps',
            name='PatientID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osa_application.patient'),
        ),
        migrations.AddField(
            model_name='spontanous_timed',
            name='PatientID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osa_application.patient'),
        ),
        migrations.AddField(
            model_name='therapieabbruch',
            name='PatientID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osa_application.patient'),
        ),
        migrations.AlterField(
            model_name='autobitlevel',
            name='eingabeID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='autobitlevel',
            name='maxEPAP',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='autobitlevel',
            name='maxPS',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='autobitlevel',
            name='minEPAP',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='autobitlevel',
            name='minPS',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='avaps',
            name='EingabeID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='avaps',
            name='Zielvolumen',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='avaps',
            name='maxEPAP',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='avaps',
            name='maxPS',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='avaps',
            name='minEPAP',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='avaps',
            name='minPS',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='spontanous_timed',
            name='AF',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='spontanous_timed',
            name='EPAP',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='spontanous_timed',
            name='IPAP',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='spontanous_timed',
            name='Modus',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='spontanous_timed',
            name='Zeitgestinsp',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='spontanous_timed',
            name='eingabeID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='therapieabbruch',
            name='Datum_Therapieabbruch',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='therapieabbruch',
            name='EingabeID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='therapieabbruch',
            name='InfobezogenerTherapieabbruch',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
