# Generated by Django 3.2.6 on 2022-01-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0020_auto_20211214_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobitlevel',
            name='PatientID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='avaps',
            name='PatientID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='PatientID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='spontanous',
            name='PatientID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='spontanous_timed',
            name='PatientID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='therapieabbruch',
            name='PatientID',
            field=models.IntegerField(default=None),
        ),
    ]
