# Generated by Django 3.2.6 on 2022-01-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0022_auto_20220108_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schlafbetreudender_Arzt',
            new_name='Schlafbetreuender_Arzt',
        ),
        migrations.AlterModelOptions(
            name='asv',
            options={'verbose_name': 'ASV', 'verbose_name_plural': 'ASV'},
        ),
        migrations.AlterModelOptions(
            name='autobitlevel',
            options={'verbose_name': 'autoBitLevel', 'verbose_name_plural': 'autoBitLevel'},
        ),
        migrations.AlterModelOptions(
            name='avaps',
            options={'verbose_name': 'AVAPS', 'verbose_name_plural': 'AVAPS'},
        ),
        migrations.AlterModelOptions(
            name='cpap_einstellung',
            options={'verbose_name': 'CPAP_Einstellung', 'verbose_name_plural': 'CPAP_Einstellung'},
        ),
        migrations.AlterModelOptions(
            name='cpap_kontrolle',
            options={'verbose_name': 'CPAP_Kontrolle', 'verbose_name_plural': 'CPAP_Kontrolle'},
        ),
        migrations.AlterModelOptions(
            name='diagnosepsg',
            options={'verbose_name': 'DiagnosePSG', 'verbose_name_plural': 'DiagnosePSG'},
        ),
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firma'},
        ),
        migrations.AlterModelOptions(
            name='gerät',
            options={'verbose_name': 'Gerät', 'verbose_name_plural': 'Gerät'},
        ),
        migrations.AlterModelOptions(
            name='masken',
            options={'verbose_name': 'Masken', 'verbose_name_plural': 'Masken'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patient'},
        ),
        migrations.AlterModelOptions(
            name='schlafbetreuender_arzt',
            options={'verbose_name': 'Schlafbetreuender_Arzt', 'verbose_name_plural': 'Schlafbetreuender_Arzt'},
        ),
        migrations.AlterModelOptions(
            name='spontanous',
            options={'verbose_name': 'Spontanous', 'verbose_name_plural': 'Spontanous'},
        ),
        migrations.AlterModelOptions(
            name='spontanous_timed',
            options={'verbose_name': 'Spontanous_Timed', 'verbose_name_plural': 'Spontanous_Timed'},
        ),
        migrations.AlterModelOptions(
            name='therapieabbruch',
            options={'verbose_name': 'Therapieabbruch', 'verbose_name_plural': 'Therapieabbruch'},
        ),
        migrations.AlterModelOptions(
            name='vorscreening',
            options={'verbose_name': 'Vorscreening', 'verbose_name_plural': 'Vorscreening'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='SVNummer',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterModelTable(
            name='schlafbetreuender_arzt',
            table='osa_Schlafbetreuender_Arzt',
        ),
    ]
