# Generated by Django 3.2.9 on 2022-01-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0023_auto_20220109_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': ' Patient', 'verbose_name_plural': ' Patient'},
        ),
    ]
