# Generated by Django 3.2.9 on 2022-01-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0025_auto_20220113_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schlafbetreuender_arzt',
            name='ArztID',
        ),
    ]
