# Generated by Django 3.2.6 on 2022-01-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0027_auto_20220122_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_medikamente',
            name='Medikament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osa_application.medikament'),
        ),
    ]
