# Generated by Django 3.2.6 on 2022-01-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0029_alter_patient_medikamente_medikament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_medikamente',
            name='Medikament',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
