# Generated by Django 3.2.6 on 2022-01-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0030_alter_patient_medikamente_medikament'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_medikamente',
            name='Gelöscht',
            field=models.BooleanField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='patient_medikamente',
            name='VerändertAm',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='patient_medikamente',
            name='VerändertVon',
            field=models.CharField(default=None, max_length=55),
        ),
    ]
