# Generated by Django 3.2.6 on 2022-01-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0033_auto_20220127_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='PatientID',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='Version',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_einstellung',
            name='BeatmungsModi',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='cpap_einstellung',
            name='Datum_cpap',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_einstellung',
            name='Erweitert',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='cpap_einstellung',
            name='IPAP',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_einstellung',
            name='PatientID',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_einstellung',
            name='Zielvolumen',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_einstellung',
            name='maxEPAP',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_einstellung',
            name='maxPS',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_einstellung',
            name='minEPAP',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_einstellung',
            name='minPS',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_kontrolle',
            name='Compliance_cpap',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_kontrolle',
            name='Datum_cpap',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_kontrolle',
            name='ModuswechselNotwendig',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_kontrolle',
            name='PatientID',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_kontrolle',
            name='berücksichtigteTage_CPAP',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_kontrolle',
            name='durchschnittlicheVerwendungsdauer',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_kontrolle',
            name='nachjustierungNotwendig',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cpap_kontrolle',
            name='restAHibei_CPAP',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='AHI_Gesamt',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='BMI_bei_Diagnose_PSG',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='Datum_Diagnose_PSG',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='Diagnose',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='Dominanz',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='Lageabhängig',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='O2unter90Prozent',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='PatientID',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='REM_assoziert',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='SaO2min_PSG',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='Zustimmung_für_Beatmung',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='alternative_Therapieempfehlung',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosepsg',
            name='primäre_Therapieempfehlung',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='firma',
            name='Firmenname',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='gerät',
            name='Freitext',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='gerät',
            name='Gerätename',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='gerät',
            name='Heizschlauch',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='gerät',
            name='Hersteller',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='gerät',
            name='Modi',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='gerät',
            name='O2Anschluss',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='gerät',
            name='PatientID',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='gerät',
            name='Rampe',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='gerät',
            name='WLB',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='gerät',
            name='vertreibendeFirma',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='masken',
            name='Größe',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='masken',
            name='Hersteller',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='masken',
            name='Maskenname',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='masken',
            name='Maskentyp',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='masken',
            name='PatientID',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Geburtsdatum',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Geschlecht',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Nachname',
            field=models.CharField(blank=True, default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Vorname',
            field=models.CharField(blank=True, default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Vorscreening',
            field=models.BooleanField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient_medikamente',
            name='Medikament',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient_medikamente',
            name='Patient',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='schlafbetreuender_arzt',
            name='Email',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='schlafbetreuender_arzt',
            name='Fachrichtung',
            field=models.CharField(blank=True, default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='schlafbetreuender_arzt',
            name='Hausnummer',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='schlafbetreuender_arzt',
            name='Name',
            field=models.CharField(blank=True, default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='schlafbetreuender_arzt',
            name='Ort',
            field=models.CharField(blank=True, default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='schlafbetreuender_arzt',
            name='Strasse',
            field=models.CharField(blank=True, default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='schlafbetreuender_arzt',
            name='Telefonnummer',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='schlafbetreuender_arzt',
            name='Vorhanden',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='schlafbetreuender_arzt',
            name='plz',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='spontanous',
            name='DeltaP',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='spontanous',
            name='EPAP',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='spontanous',
            name='IPAP',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='spontanous',
            name='PatientID',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='spontanous',
            name='verordnetam',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='therapieabbruch',
            name='Datum_Therapieabbruch',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='therapieabbruch',
            name='InfobezogenerTherapieabbruch',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='therapieabbruch',
            name='PatientID',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='vorscreening',
            name='DatumderPG',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='vorscreening',
            name='PGdurchgeführtvon',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='vorscreening',
            name='RDI',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='vorscreening',
            name='sao2minPG',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('PatientID', 'Version')},
        ),
    ]
