# Generated by Django 3.2.6 on 2022-01-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0034_auto_20220127_1334'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
    ]
