# Generated by Django 3.2.6 on 2022-01-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osa_application', '0035_alter_patient_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpap_einstellung',
            name='Set',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='cpap_einstellung',
            name='Version',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='cpap_kontrolle',
            name='Set',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='cpap_kontrolle',
            name='Version',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='diagnosepsg',
            name='Set',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='diagnosepsg',
            name='Version',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='firma',
            name='Set',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='firma',
            name='Version',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='gerät',
            name='Set',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='gerät',
            name='Version',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='masken',
            name='Set',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='masken',
            name='Version',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='patient_medikamente',
            name='Set',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='patient_medikamente',
            name='Version',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='schlafbetreuender_arzt',
            name='Set',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='schlafbetreuender_arzt',
            name='Version',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='spontanous',
            name='Set',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='spontanous',
            name='Version',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='therapieabbruch',
            name='Set',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='therapieabbruch',
            name='Version',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='vorscreening',
            name='Set',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='vorscreening',
            name='Version',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
